### PR TITLE
Fix CorrelatedWienerProcess

### LINKED ISSUE #83: Update dist function for out of place cases
It seems that we need to update, for the out of place case, the following line:
https://github.com/SciML/DiffEqNoiseProcess.jl/blob/68a8391edc408b42d692035d9583b8d2738d9548/src/correlated_noisefunc.jl#L4

For the in place case it is updated:
https://github.com/SciML/DiffEqNoiseProcess.jl/blob/68a8391edc408b42d692035d9583b8d2738d9548/src/correlated_noisefunc.jl#L22

Otherwise when I use the out of place form for a `CorrelatedWienerProcess` I  get a `MethodError` because it cannot evaluate `W.dist(W.dW,W,dtleft,u,p,W.curt,W.rng)` here:
https://github.com/SciML/DiffEqNoiseProcess.jl/blob/68a8391edc408b42d692035d9583b8d2738d9548/src/noise_interfaces/noise_process_interface.jl#L150

This is a MWE that should pass (its in place counterpart works, as expected):
```julia
f(u, p, t) = SVector(0.1, 0.1)
g(u, p, t) = SVector(0.1, 0.1)
Γ = @SMatrix [1.0 0.3
              0.3 1.0]
noise = CorrelatedWienerProcess(Γ, 0., @SVector(zeros(2)), @SVector(zeros(2)))
prob = SDEProblem{false}(f, g, @SVector(ones(2)), (0., 1.), nothing, noise = noise)
sol = solve(prob, SRIW1())
```

Thanks!

### PR DESCRIPTION
**Pull request by frankschae**
fixes #83. Looks like there were no tests for the `CorrelatedWienerProcess` before.

### CODE REVIEW

**Comment by frankschae** [comment]
What does "by translation" mean @mschauer ? Do you have a link/write up? Then I'll add it here as well.

**Comment by frankschae** [comment]
What does "by translation" mean @mschauer ? Do you have a link/write up? Then I'll add it here as well.

**Comment by mschauer** [comment]
Essentially https://github.com/mschauer/Bridge.jl/blob/137b811a6ad4c966c2876738233fbe41b2c4ca1a/src/wiener.jl#L72, only with correlated noise

**Comment by ChrisRackauckas** [comment]
>only with correlated noise

image

**Comment by frankschae** [comment]
This one is good to go. I think it's probably best to shift the bridge to a follow up (and open an issue with the link from above)

**Comment by rvignolo** [comment]
thank you @frankschae!

**Comment by mschauer** [comment]
The implementation isn't the big problem, that just a variant of `t ↦ (t/(T-S)⋅a + σ⋅(W(t-S)) + t/(T-S)⋅(b-σ⋅W(T-S))` for a bridge from `a` at time`S` to `b` at time `T`. That it _is_ the bridge, that deserves a check.

**Pull request merged**
